### ISSUE TITLE
Identify missed notifications

### ISSUE THREAD

**Issue by stephenmichaelf** [karelz/GitHubIssues#163] opened 2017-05-20 15:55 UTC
Identify **which notifications were missed** by "WebHook" - note: we might have missed not the last notification, but the one before. Can we somehow easily detect that?

@karelz need some clarification on this and differences to #162

**Comment by karelz** [comment] 2017-05-21 05:25
This is dupe of #162

**Closed as completed by karelz** 2017-05-21 05:25 UTC
Labels: P2, feature, area-Notifications
